class AppStrings {
  AppStrings(this.localeCode);

  final String localeCode;
  bool get isRu => localeCode == 'ru';

  String t(String key) => (_values[key] ?? const {})[localeCode] ?? key;

  static const Map<String, Map<String, String>> _values = {
    'subtitle': {'ru': 'Моя мастерская', 'en': 'Your repair workshop'},
    'start': {'ru': 'Начать работу', 'en': 'Start working'},
    'continue': {'ru': 'Продолжить', 'en': 'Continue'},
    'back': {'ru': 'Назад', 'en': 'Back'},
    'save': {'ru': 'Сохранить', 'en': 'Save'},
    'cancel': {'ru': 'Отмена', 'en': 'Cancel'},
    'delete': {'ru': 'Удалить', 'en': 'Delete'},
    'edit': {'ru': 'Изменить', 'en': 'Edit'},
    'language': {'ru': 'Язык', 'en': 'Language'},
    'workshop': {'ru': 'Мастерская', 'en': 'Workshop'},
    'workshopName': {'ru': 'Название мастерской', 'en': 'Workshop name'},
    'phone': {'ru': 'Телефон', 'en': 'Phone'},
    'address': {'ru': 'Адрес', 'en': 'Address'},
    'currency': {'ru': 'Валюта', 'en': 'Currency'},
    'required': {'ru': 'Заполните это поле', 'en': 'This field is required'},
    'home': {'ru': 'Главная', 'en': 'Home'},
    'orders': {'ru': 'Заказы', 'en': 'Orders'},
    'customers': {'ru': 'Клиенты', 'en': 'Customers'},
    'inventory': {'ru': 'Склад', 'en': 'Inventory'},
    'more': {'ru': 'Ещё', 'en': 'More'},
    'overview': {'ru': 'Обзор мастерской', 'en': 'Workshop overview'},
    'newOrder': {'ru': 'Новый заказ', 'en': 'New order'},
    'activeOrders': {'ru': 'Активные заказы', 'en': 'Active orders'},
    'readyPickup': {'ru': 'Готовы к выдаче', 'en': 'Ready for pickup'},
    'overdue': {'ru': 'Просрочены', 'en': 'Overdue'},
    'receivedToday': {'ru': 'Получено сегодня', 'en': 'Received today'},
    'upcoming': {'ru': 'Ближайшие сроки', 'en': 'Upcoming deadlines'},
    'recent': {'ru': 'Последние действия', 'en': 'Recent activity'},
    'showAll': {'ru': 'Показать все', 'en': 'Show all'},
    'emptyOrders': {'ru': 'Первый ремонт начинается здесь', 'en': 'Your first repair starts here'},
    'emptyCustomers': {'ru': 'Клиентов пока нет', 'en': 'No customers yet'},
    'emptyInventory': {'ru': 'Склад пока пуст', 'en': 'Inventory is empty'},
    'search': {'ru': 'Поиск', 'en': 'Search'},
    'all': {'ru': 'Все', 'en': 'All'},
    'today': {'ru': 'Сегодня', 'en': 'Today'},
    'ready': {'ru': 'Готовы', 'en': 'Ready'},
    'debt': {'ru': 'Долг', 'en': 'Debt'},
    'customer': {'ru': 'Клиент', 'en': 'Customer'},
    'name': {'ru': 'Имя', 'en': 'Name'},
    'note': {'ru': 'Заметка', 'en': 'Note'},
    'device': {'ru': 'Устройство', 'en': 'Device'},
    'category': {'ru': 'Категория', 'en': 'Category'},
    'model': {'ru': 'Бренд и модель', 'en': 'Brand and model'},
    'problem': {'ru': 'Неисправность', 'en': 'Reported issue'},
    'condition': {'ru': 'Состояние при приёме', 'en': 'Condition at intake'},
    'serial': {'ru': 'Серийный номер / IMEI', 'en': 'Serial number / IMEI'},
    'workAndDeadline': {'ru': 'Работа и срок', 'en': 'Work and deadline'},
    'priority': {'ru': 'Приоритет', 'en': 'Priority'},
    'normal': {'ru': 'Обычный', 'en': 'Normal'},
    'high': {'ru': 'Высокий', 'en': 'High'},
    'urgent': {'ru': 'Срочный', 'en': 'Urgent'},
    'deadline': {'ru': 'Обещанный срок', 'en': 'Promised deadline'},
    'estimate': {'ru': 'Предварительная стоимость', 'en': 'Estimated price'},
    'deposit': {'ru': 'Предоплата', 'en': 'Deposit'},
    'review': {'ru': 'Проверка и приём', 'en': 'Review and intake'},
    'acceptDevice': {'ru': 'Принять устройство', 'en': 'Accept device'},
    'orderCreated': {'ru': 'Заказ создан', 'en': 'Order created'},
    'order': {'ru': 'Заказ', 'en': 'Order'},
    'status': {'ru': 'Статус', 'en': 'Status'},
    'payment': {'ru': 'Оплата', 'en': 'Payment'},
    'history': {'ru': 'История', 'en': 'History'},
    'works': {'ru': 'Работы', 'en': 'Work'},
    'total': {'ru': 'Итого', 'en': 'Total'},
    'paid': {'ru': 'Получено', 'en': 'Paid'},
    'balance': {'ru': 'Осталось оплатить', 'en': 'Amount due'},
    'addPayment': {'ru': 'Добавить оплату', 'en': 'Record payment'},
    'amount': {'ru': 'Сумма', 'en': 'Amount'},
    'method': {'ru': 'Способ', 'en': 'Method'},
    'cash': {'ru': 'Наличные', 'en': 'Cash'},
    'transfer': {'ru': 'Перевод', 'en': 'Transfer'},
    'card': {'ru': 'Карта', 'en': 'Card'},
    'other': {'ru': 'Другое', 'en': 'Other'},
    'nextStatus': {'ru': 'Следующий этап', 'en': 'Next stage'},
    'exportPdf': {'ru': 'Документ PDF', 'en': 'PDF document'},
    'addCustomer': {'ru': 'Добавить клиента', 'en': 'Add customer'},
    'addPart': {'ru': 'Добавить запчасть', 'en': 'Add part'},
    'part': {'ru': 'Запчасть', 'en': 'Part'},
    'stock': {'ru': 'Остаток', 'en': 'Stock'},
    'minimum': {'ru': 'Минимальный остаток', 'en': 'Minimum stock'},
    'buyPrice': {'ru': 'Закупочная цена', 'en': 'Purchase price'},
    'salePrice': {'ru': 'Цена продажи', 'en': 'Selling price'},
    'addStock': {'ru': 'Поступление', 'en': 'Stock receipt'},
    'writeOff': {'ru': 'Списать', 'en': 'Write off'},
    'tasks': {'ru': 'Задачи', 'en': 'Tasks'},
    'finance': {'ru': 'Финансы', 'en': 'Finance'},
    'reports': {'ru': 'Отчёты', 'en': 'Reports'},
    'employees': {'ru': 'Сотрудники', 'en': 'Employees'},
    'services': {'ru': 'Услуги', 'en': 'Services'},
    'settings': {'ru': 'Настройки', 'en': 'Settings'},
    'appearance': {'ru': 'Оформление', 'en': 'Appearance'},
    'system': {'ru': 'Системная', 'en': 'System'},
    'light': {'ru': 'Светлая', 'en': 'Light'},
    'dark': {'ru': 'Тёмная', 'en': 'Dark'},
    'backup': {'ru': 'Резервная копия', 'en': 'Backup'},
    'restore': {'ru': 'Восстановить данные', 'en': 'Restore data'},
    'exportCsv': {'ru': 'Экспорт заказов CSV', 'en': 'Export orders CSV'},
    'about': {'ru': 'О приложении', 'en': 'About'},
    'developed': {'ru': 'Разработано NEXVIRO', 'en': 'Developed by NEXVIRO'},
    'developer': {'ru': 'Разработчик: Юсуф', 'en': 'Developer: Yusuf'},
    'version': {'ru': 'Версия 1.0.0', 'en': 'Version 1.0.0'},
    'saved': {'ru': 'Сохранено', 'en': 'Saved'},
    'errorSave': {'ru': 'Не удалось сохранить. Попробуйте ещё раз.', 'en': "Couldn't save. Please try again."},
    'invalidAmount': {'ru': 'Введите корректную сумму', 'en': 'Enter a valid amount'},
    'noData': {'ru': 'Пока нет данных', 'en': 'No data yet'},
    'successBackup': {'ru': 'Резервная копия создана', 'en': 'Backup created'},
    'successRestore': {'ru': 'Данные восстановлены', 'en': 'Data restored'},
    'demo': {'ru': 'Демо', 'en': 'Demo'},
  };

  String status(String key) => {
        'received': isRu ? 'Принят' : 'Received',
        'diagnosing': isRu ? 'Диагностика' : 'Diagnosing',
        'awaiting_approval': isRu ? 'На согласовании' : 'Awaiting approval',
        'awaiting_parts': isRu ? 'Ждём запчасть' : 'Awaiting parts',
        'in_progress': isRu ? 'В работе' : 'In progress',
        'ready': isRu ? 'Готов' : 'Ready for pickup',
        'delivered': isRu ? 'Выдан' : 'Delivered',
        'cancelled': isRu ? 'Отменён' : 'Cancelled',
      }[key] ?? key;
}
